apiVersion: apps/v1
kind: Deployment
metadata:
  name: fca-client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fca-client
  template:
    metadata:
      labels:
        app: fca-client
    spec:
      containers:
        - name: fca-client
          image: localhost:5000/fca-client:1
          envFrom:
            - configMapRef:
                name: fca-client-configmap
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fca-client-service
spec:
  type: NodePort
  selector:
    app: fca-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
