apiVersion: apps/v1
kind: Deployment
metadata:
  name: fca-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fca-server
  template:
    metadata:
      labels:
        app: fca-server
    spec:
      containers:
        - name: fca-server
          image: avinashrajure/fca-server:cd20af0aa8231142d99c8aa55c794e1e3c15137f
          envFrom:
            - secretRef:
                name: fca-server-secret
          ports:
            - containerPort: 7777

---
apiVersion: v1
kind: Service
metadata:
  name: fca-server-service
spec:
  selector:
    app: fca-server
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
